TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 48
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /xxx/tools/checkpoints/SLOWFAST_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
#  PATH_TO_DATA_DIR: /home/chenxi/SlowFast_tst/renameData
#  PATH_TO_DATA_DIR: /home/chenxi/dataset/train_data/train_data
  PATH_TO_DATA_DIR: /home/chenxi/dataset/actionData/train_data
#  PATH_TO_DATA_DIR: /home/bruce/bigVolumn/autolabelData/train_data/train_data
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 37
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 35  # 1:35,2:100
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 3
  ARCH: slowfast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 32
#  CHECKPOINT_FILE_PATH: /home/chenxi/SlowFast_tst/SlowFast-master0329/SlowFast-master/tools/checkpoints_7/checkpoints/checkpoint_epoch_00300.pyth
  CHECKPOINT_FILE_PATH: /home/bruce/bigVolumn/autolabelData/humanActionModel/checkpoints_7checkpoints/checkpoint_epoch_00300.pyth
  #  CHECKPOINT_FILE_PATH: /xxx/tools/checkpoints_3/checkpoints/checkpoint_epoch_00196.pyth
  #   CHECKPOINT_FILE_PATH: /home/chenxi/SlowFast_tst/SlowFast-master0329/SlowFast-master/tools/checkpoints_2/checkpoints/checkpoint_epoch_00184.pyth
  #   CHECKPOINT_FILE_PATH: /home/chenxi/SlowFast_tst/SlowFast-master0329/SlowFast-master/tools/checkpoints_4/checkpoints/checkpoint_epoch_00213.pyth
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./checkpoints
